import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { Badge, Empty, Table, PageSpinner } from '../components/shared/UI';
import { FileText, FileDown, Loader2 } from 'lucide-react';
import CoalTestReport from '../components/CoalTestReport';
function groupBySample(tests) {
  const map = new Map();
  tests.forEach(t => {
    const sid = t.sample_db_id;
    if (!map.has(sid)) {
      map.set(sid, {
        sample_db_id:    sid,
        sample_ref_id:   t.sample_ref_id,
        lab_internal_id: t.lab_internal_id,
        group_ref_id:    t.group_ref_id,
        client_name:     t.client_name,
        tests: [],
      });
    }
    map.get(sid).tests.push(t);
  });
  return Array.from(map.values());
}

export default function ReportsPage() {
  const [tests,      setTests]      = useState([]);
  const [groups,     setGroups]     = useState([]);
  const [sampleMeta, setSampleMeta] = useState({});
  const [loading,    setLoading]    = useState(true);
  const [view,       setView]       = useState('samples');

  // Report viewer state
  const [reportData, setReportData] = useState(null); // { sample, tests }
  const [loadingReport, setLoadingReport] = useState({});

  useEffect(() => {
    Promise.all([api.getTests(), api.getSampleGroups(), api.getSamples()])
      .then(([t, g, s]) => {
        setTests(t);
        setGroups(g);
        const meta = {};
        s.forEach(sample => {
          meta[sample.id] = { test_count: sample.test_count, approved_count: sample.approved_count };
        });
        setSampleMeta(meta);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const openReport = async (sampleId) => {
    setLoadingReport(p => ({ ...p, [sampleId]: true }));
    try {
      const data = await api.getSampleReport(sampleId);
      if (!data.tests.length) return alert('No approved tests for this sample yet.');
      setReportData(data);
    } catch (e) { alert(e.message); }
    finally { setLoadingReport(p => ({ ...p, [sampleId]: false })); }
  };

  const downloadGroup = async (groupId, setDl) => {
    setDl(p => ({ ...p, [groupId]: true }));
    try {
      const { group, tests } = await api.getGroupReport(groupId);
      if (!tests.length) return alert('No approved tests in this group yet.');

      // Load html2pdf.js from CDN if not already loaded
      if (!window.html2pdf) {
        await new Promise((resolve, reject) => {
          const script = document.createElement('script');
          script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
          script.onload = resolve;
          script.onerror = () => reject(new Error('Failed to load PDF library'));
          document.head.appendChild(script);
        });
      }

      // Build the report HTML in a hidden off-screen element
      const rows = tests.map(t =>
        `<tr><td>${t.sample_ref_id}</td><td>${t.lab_internal_id||'—'}</td><td>${t.test_name}</td><td>${t.result_value}</td><td>${t.test_unit||'—'}</td><td>${t.chemist_name||'—'}</td></tr>`
      ).join('');

      const container = document.createElement('div');
      container.style.cssText = 'position:fixed;left:-9999px;top:0;width:794px;background:#fff;font-family:serif;font-size:12px;padding:30px;';
      container.innerHTML = `
        <h2 style="margin-bottom:4px;font-size:16px;">Group Analysis Report — ${group.group_ref_id}</h2>
        <p style="margin:2px 0 16px;color:#555;font-size:13px;">Client: ${group.client_name} &nbsp;|&nbsp; Contact: ${group.contact_person||'—'}</p>
        <table style="width:100%;border-collapse:collapse;">
          <thead><tr style="background:#f0f0f0;">
            <th style="border:1px solid #000;padding:6px 10px;text-align:left;">Sample Ref</th>
            <th style="border:1px solid #000;padding:6px 10px;text-align:left;">Lab ID</th>
            <th style="border:1px solid #000;padding:6px 10px;text-align:left;">Parameter</th>
            <th style="border:1px solid #000;padding:6px 10px;text-align:left;">Result</th>
            <th style="border:1px solid #000;padding:6px 10px;text-align:left;">Unit</th>
            <th style="border:1px solid #000;padding:6px 10px;text-align:left;">Analyst</th>
          </tr></thead>
          <tbody>${rows}</tbody>
        </table>
        <p style="margin-top:20px;font-size:11px;color:#888;">Generated by CoalLIMS · ${new Date().toLocaleDateString()}</p>
      `;
      document.body.appendChild(container);

      const filename = `GroupReport_${group.group_ref_id}.pdf`;
      await window.html2pdf()
        .set({
          margin: [10, 10, 10, 10],
          filename,
          image: { type: 'jpeg', quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true, logging: false },
          jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        })
        .from(container)
        .save();

      document.body.removeChild(container);
    } catch (e) { alert(e.message); }
    finally { setDl(p => ({ ...p, [groupId]: false })); }
  };

  const [dlGroupLoading, setDlGroupLoading] = useState({});

  // If report is open, show full-screen report viewer
  if (reportData) {
    return (
      <CoalTestReport
        sample={reportData.sample}
        tests={reportData.tests}
        onClose={() => setReportData(null)}
      />
    );
  }

  if (loading) return <PageSpinner />;

  const sampleRows = groupBySample(tests);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
        <p className="text-sm text-gray-500 mt-0.5">
          Each sample gets one report containing all its approved tests.
        </p>
      </div>

      <div className="flex gap-2 border-b border-gray-100">
        {[{ key: 'samples', label: 'By Sample' }, { key: 'groups', label: 'By Group' }].map(tab => (
          <button key={tab.key} onClick={() => setView(tab.key)}
            className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-px ${
              view === tab.key ? 'border-brand-600 text-brand-700' : 'border-transparent text-gray-500 hover:text-gray-700'}`}>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Per-sample reports */}
      {view === 'samples' && (
        <Table headers={['Lab Internal ID', 'Sample Ref ID', 'Group', 'Client', 'Approved Tests', 'Report']} loading={false}>
          {sampleRows.length === 0
            ? <tr><td colSpan={6}><Empty message="No approved tests yet." icon={FileText} /></td></tr>
            : sampleRows.map(s => {
              const meta        = sampleMeta[s.sample_db_id];
              const allApproved = meta && meta.test_count > 0 && meta.approved_count === meta.test_count;
              return (
                <tr key={s.sample_db_id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-4 py-3 font-mono text-sm font-semibold text-blue-700">{s.lab_internal_id || '—'}</td>
                  <td className="px-4 py-3 font-mono text-sm text-gray-600">{s.sample_ref_id}</td>
                  <td className="px-4 py-3 font-mono text-sm text-gray-500">{s.group_ref_id}</td>
                  <td className="px-4 py-3 text-sm text-gray-500">{s.client_name}</td>
                  <td className="px-4 py-3">
                    <div className="flex flex-wrap gap-1">
                      {s.tests.map(t => (
                        <span key={t.id} className="badge bg-green-50 text-green-700 text-xs">{t.test_name}</span>
                      ))}
                    </div>
                  </td>
                  <td className="px-4 py-3">
                    {allApproved ? (
                      <button
                        onClick={() => openReport(s.sample_db_id)}
                        disabled={loadingReport[s.sample_db_id]}
                        className="btn-primary py-1 px-3 text-xs">
                        {loadingReport[s.sample_db_id]
                          ? <Loader2 size={12} className="animate-spin" />
                          : <FileText size={12} />}
                        View Report
                      </button>
                    ) : (
                      <span className="text-xs text-amber-600 bg-amber-50 border border-amber-100 px-2 py-1 rounded-lg font-medium">
                        {meta ? `${meta.approved_count}/${meta.test_count} approved` : 'Pending'}
                      </span>
                    )}
                  </td>
                </tr>
              );
            })}
        </Table>
      )}

      {/* Group reports */}
      {view === 'groups' && (
        <Table headers={['Group Ref ID', 'Client', 'Samples', 'Status', 'Download']} loading={false}>
          {groups.length === 0
            ? <tr><td colSpan={5}><Empty message="No groups available." icon={FileText} /></td></tr>
            : groups.map(g => (
              <tr key={g.id} className="hover:bg-gray-50 transition-colors">
                <td className="px-4 py-3 font-mono text-sm font-semibold text-gray-800">{g.group_ref_id}</td>
                <td className="px-4 py-3 text-sm text-gray-600">{g.client_name}</td>
                <td className="px-4 py-3 text-sm text-gray-500">{g.sample_count} sample(s)</td>
                <td className="px-4 py-3"><Badge status={g.status} /></td>
                <td className="px-4 py-3">
                  <button onClick={() => downloadGroup(g.id, setDlGroupLoading)}
                    disabled={dlGroupLoading[g.id]} className="btn-primary py-1 px-3 text-xs">
                    {dlGroupLoading[g.id] ? <Loader2 size={12} className="animate-spin" /> : <FileDown size={12} />}
                    Download PDF
                  </button>
                </td>
              </tr>
            ))}
        </Table>
      )}
    </div>
  );
}